-- MySQL Script generated by MySQL Workbench
-- Wed Feb 10 20:47:56 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GFAphonesDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GFAphonesDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GFAphonesDB` DEFAULT CHARACTER SET utf8 ;
USE `GFAphonesDB` ;

-- -----------------------------------------------------
-- Table `GFAphonesDB`.`SmartPhone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GFAphonesDB`.`SmartPhone` (
  `ID_SmartPhone` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nom_SP` VARCHAR(45) NOT NULL,
  `Brand` VARCHAR(45) NOT NULL,
  `Prix` DECIMAL(2,3) UNSIGNED NOT NULL,
  `Quantite` INT NULL,
  `Color` VARCHAR(45) NULL,
  `Reference` VARCHAR(45) NULL,
  `Ecran` VARCHAR(45) NULL,
  `Processeur` VARCHAR(45) NULL,
  `Systeme_Exploit` VARCHAR(45) NULL,
  `Appareil_Photo` VARCHAR(45) NULL,
  `Ram` VARCHAR(45) NULL,
  `Stockage` VARCHAR(45) NULL,
  `Batterie` VARCHAR(45) NULL,
  `Double_Sim` TINYINT NULL,
  PRIMARY KEY (`ID_SmartPhone`),
  UNIQUE INDEX `ID_UNIQUE` (`ID_SmartPhone` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GFAphonesDB`.`Accessoire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GFAphonesDB`.`Accessoire` (
  `ID_Accessoire` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(45) NULL,
  `Reference` VARCHAR(45) NOT NULL,
  `Color` VARCHAR(45) NULL,
  `Quantite` INT NOT NULL,
  `Prix` DECIMAL(2,3) NOT NULL,
  `Nom_Ac` VARCHAR(45) NULL,
  `Brand_Ac` VARCHAR(45) NULL,
  `ID_SmartPhone` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID_Accessoire`),
  UNIQUE INDEX `ID_accessoire_UNIQUE` (`ID_Accessoire` ASC) VISIBLE,
  UNIQUE INDEX `ID_SmartPhone_UNIQUE` (`ID_SmartPhone` ASC) VISIBLE,
  CONSTRAINT `ID_SmartPhone`
    FOREIGN KEY (`ID_SmartPhone`)
    REFERENCES `GFAphonesDB`.`SmartPhone` (`ID_SmartPhone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GFAphonesDB`.`Promo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GFAphonesDB`.`Promo` (
  `ID_Promo` INT NOT NULL AUTO_INCREMENT,
  `ID_SmartPhone` INT UNSIGNED NOT NULL,
  `ID_Accessoire` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID_Promo`),
  UNIQUE INDEX `ID_Promo_UNIQUE` (`ID_Promo` ASC) VISIBLE,
  UNIQUE INDEX `ID_SmartPhone_UNIQUE` (`ID_SmartPhone` ASC) VISIBLE,
  UNIQUE INDEX `ID_Accessoire_UNIQUE` (`ID_Accessoire` ASC) VISIBLE,
  CONSTRAINT `ID_SmartPhone`
    FOREIGN KEY (`ID_SmartPhone`)
    REFERENCES `GFAphonesDB`.`SmartPhone` (`ID_SmartPhone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_Accessoire`
    FOREIGN KEY (`ID_Accessoire`)
    REFERENCES `GFAphonesDB`.`Accessoire` (`ID_Accessoire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
